
// Request Actions
export const MAKE_REQUEST = "MAKE_REQUEST";
export const REQUEST_GET_ALL_SUCCESS = "REQUEST_GET_ALL_SUCCESS";
export const REQUEST_GET_ALL_FAILURE = "REQUEST_GET_ALL_FAILURE";

export const OPEN_POPUP = "OPEN_POPUP";
export const REQUEST_ADD_SUCCESS = "REQUEST_ADD_SUCCESS";
export const REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
export const REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";

export const REQUEST_GET_BY_CODE_SUCCESS = "REQUEST_GET_BY_CODE_SUCCESS";
